# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

def even_fib_gen():
    a, b = 1, 2
    yield b 
    while True:
        a, b = b, a+b
        if (b%2 == 0):
            yield b

fib = even_fib_gen()

sum = 0
val = fib.next()
while val < 4000000:
    sum += val
    val = fib.next()

print sum

